language: node_js
node_js:
- 7.7.1
after_script:
- scp -o StrictHostKeyChecking=no app.js lin@47.88.220.215:/home/test/
before_install:
- openssl aes-256-cbc -K $encrypted_30a204b2b5f9_key -iv $encrypted_30a204b2b5f9_iv
  -in id_rsa.travis.enc -out id_rsa.travis -d
